EMPTY_INGREDIENTS_ERROR = 'Отсутствуют ингредиенты'
EMPTY_TAGS_ERROR = 'Отсутствуют теги'
DOUBLE_INGREDIENT_ERROR = 'Повтор ингредиентов'
DOUBLE_TAG_ERROR = 'Повтор тегов'
FAVORITES_DELETE_MESSAGE = 'Рецепт удален из избранного'
FAVORITES_EXISTS_MESSAGE = 'Рецепт уже в избранном'
NO_COLOR_NAME_ERROR = 'Для этого цвета нет имени'
NOT_IN_FAVORITES_MESSAGE = 'Рецепт не находится в избранном'
NOT_IN_SHOP_CART_MESSAGE = 'Рецепт не находится в списке покупок'
NULL_FIELD_ERROR = 'Значение не может равняться нулю'
RECIPE_ALREADY_EXISTS_ERROR = "Данный рецепт уже существует"
RECIPE_DOES_NOT_EXIST = "Такого рецепта нет"
SHOP_CART_DELETE_MESSAGE = 'Рецепт удален из списка покупок'
SHOP_CART_EXISTS_MESSAGE = 'Рецепт уже в списке покупок'
