# Generated by Django 4.2.6 on 2023-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=321, upload_to='recipes/images', verbose_name='Фото блюда'),
            preserve_default=False,
        ),
    ]
