# Generated by Django 4.2.6 on 2023-11-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_measure_ingredient_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
