# Generated by Django 4.2.6 on 2023-11-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement',
            new_name='measurement_unit',
        ),
    ]
