# Generated by Django 4.2.6 on 2023-11-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_favorites_unique_recipe_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorites',
            name='unique_recipe_user',
        ),
    ]
