# Generated by Django 4.2.6 on 2023-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Фото блюда'),
            preserve_default=False,
        ),
    ]
