# Generated by Django 4.2.6 on 2023-11-14 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время готовки должно быть больше или равно 1. Введите допустимое значение'), django.core.validators.MaxValueValidator(32767, message='Время готовки должно быть меньше или равно 32767. Введите допустимое значение.')], verbose_name='Время приготовления (мин.)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)], verbose_name='Количество'),
        ),
    ]
