# Generated by Django 4.2.6 on 2023-11-14 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингрендиентов не должно быть меньше 1. Введите допустимое значение'), django.core.validators.MaxValueValidator(32767, message='Количество ингрендиентов не должно быть больше 32767. Введите допустимое значение')], verbose_name='Количество'),
        ),
    ]
