# Generated by Django 4.2.6 on 2023-11-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_name_measurement_unit',
        ),
    ]
