# Generated by Django 4.2.6 on 2023-11-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_name_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dop',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
