# Generated by Django 4.2.6 on 2023-11-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_dop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dop',
        ),
    ]
